[features]
seeds = false
skip-lint = false
[programs.localnet]
sigorg = "83X8rd5T7NDFiqHWGVgCLDx1jLMjEEg9JqxWQm52dpEK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/clementforjanic/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
copy-idl = "cp target/idl/*.json app/src/types"
